### ISSUE TITLE
Videos don't save if photos permission for the app is "Selected Photos" iOS14

### ISSUE THREAD

**Issue by sevenpastzeero** [haoict/twitter-no-ads#12]
As the title says. When trying to save a video from Twitter app, while the permission is "Selected Photos", the download reaches 100% and stop.
Is there a fix for this, or is it a limitation?
Thanks for your great tweaks.

**Comment by haoict** [comment]
Please update "libhdev", I think it will fix it, otherwise please reopen the issue.
