### ISSUE TITLE
Can’t see list of accounts in a reply 

### ISSUE THREAD

**Issue by WorksbyBBS** [haoict/twitter-no-ads#2]
When I want to rely to a tweet that has multiple accounts mentioned, and I want to deselect accounts, it doesn’t show me the list (just shows a check mark for “others in the conversation”) and sometimes doesn’t even show that option.

I disabled this tweak in iCleaner, and the problem was solved, so I’m certain it’s causing this issue for some reason

**Comment by haoict** [comment]
I can confirm the bug. An update version will be rolled out soon.
Thank you so much

**Comment by haoict** [comment]
Hi,
I updated to version 1.2.1.
Should fix this issue. Could you please check?

**Comment by WorksbyBBS** [comment]
Hi,

Thank you for the response!
It seems solved :)

Best Regards,
Alo

🐦 alolastmoment
📧 bbscydia@gmail.com
🌐 https://worksbybbs.github.io
