### ISSUE TITLE
Twitter version 8.20

### ISSUE THREAD

**Issue by w6511** [haoict/twitter-no-ads#4]
Hi,
1. Long press video cannot be saved.
2. Can you add the feature to block twitter ads that are pointed by red arrows?
![20200530_161309000_iOS](https://user-images.githubusercontent.com/65994118/83333823-26264f00-a2d5-11ea-93de-fd7c675fe5b2.jpg)
![20200530_161410000_iOS](https://user-images.githubusercontent.com/65994118/83333835-2d4d5d00-a2d5-11ea-8c37-28ff2d7d22b5.png)

**Comment by haoict** [comment]
Hi,
1. Long press video cannot be saved.
-> You have to tap to view video first, when you can see seek slider, you can long press :)
2. Can you add the feature to block twitter ads that are pointed by red arrows?
-> I myself don't see it. I will remove it if I can see it in future. Thanks for suggestion.

**Comment by w6511** [comment]
Please look at the gif I sent, there is no option to download.
![20200530-164041000-iOS](https://user-images.githubusercontent.com/65994118/83334288-047a9700-a2d8-11ea-906f-c874e517adae.gif)

**Comment by haoict** [comment]
If you have any jailbreak bypass tweak (UnSub, FlyJb, shadow,...), please try to whitelist my tweak

**Comment by w6511** [comment]
But I did not use any jailbreak bypass tweak.

**Comment by haoict** [comment]
I'd suggest you to check Setting that "Can Save Video" option is on.

Then please follow these instructions:

1. Install FLEXing https://moreinfo.thebigboss.org/moreinfo/depiction.php?file=flexingDp
2. Respring after installing
3. Open Twitter
4. Hold on the Status Bar to open the FLEX toolbar
5. Tap the "Menu" button
6. Tap "Runtime Browser"
7. Search for "twitternoads"
8. Does "twitternoads.dylib" appear?

If yes: Please share your twitter account, or you can add me at https://twitter.com/haoict. I will DM you to follow up and debug

If no: seems like there is problem with your device, it can not load the tweak, not the problem with the tweak itself.

**Comment by w6511** [comment]
The Twitter no ads tweak is not displayed in the settings, and the option "Can Save Video" is not seen. I downloaded it from the bigboss source.
![20200530_165725000_iOS](https://user-images.githubusercontent.com/65994118/83334615-4ad0f580-a2da-11ea-9d11-a41571d738ff.png)

**Comment by haoict** [comment]
Ah that's why. The one from BigBoss is very old one, please add my repo and update it
https://haoict.github.io/cydia

**Comment by w6511** [comment]
Great, it works. Thank you very much.
