### ISSUE TITLE
URL preview images not there

### ISSUE THREAD

**Issue by WorksbyBBS** [haoict/twitter-no-ads#5]
With the tweak enabled, the preview image for URLs doesn’t show. I have tried disabling all options to no avail. When I disabled the tweak with iCleaner to check, preview images were working again.

**Comment by haoict** [comment]
Hi @WorksbyBBS 
Could you capture screenshot for "preview image for URLs"?

**Comment by WorksbyBBS** [comment]
Hi,

Screenshot is attached. It’s for all the urls similar to how the news tweets show.

Best Regards,
Alo

🐦 alolastmoment
📧 bbscydia@gmail.com
🌐 https://worksbybbs.github.io

**Comment by haoict** [comment]
@WorksbyBBS 
I can't see any screenshot, can you upload again?

**Comment by WorksbyBBS** [comment]
Best Regards,
Alo

🐦 alolastmoment
📧 bbscydia@gmail.com
🌐 https://worksbybbs.github.io

**Comment by haoict** [comment]
![image](https://user-images.githubusercontent.com/7247750/83585767-b094da00-a585-11ea-81fa-d7d8b6ba4da7.png)
this is what I see :-s

**Comment by WorksbyBBS** [comment]
Cuz I’ve been replying from email. I’ll try directly from github. 
![E5735114-14FD-4793-89A4-545081E72B22](https://user-images.githubusercontent.com/21962896/83586111-53ccfb80-a554-11ea-9056-c29bf4d254e9.jpeg)

**Comment by k1nzu** [comment]
> Cuz I’ve been replying from email. I’ll try directly from github.
> ![E5735114-14FD-4793-89A4-545081E72B22](https://user-images.githubusercontent.com/21962896/83586111-53ccfb80-a554-11ea-9056-c29bf4d254e9.jpeg)

I’m facing the same problem.

**Comment by k1nzu** [comment]
Just found out myself. It happens when you disable Twitter analytic URL.

**Comment by w6511** [comment]
Hi @haoict  
Is it possible to open the Skip Analytic URL option, but can display the preview image of the website?

**Comment by Greigh** [comment]
![862F56C7-530F-46B2-9CA1-50EE23B04FBE](https://user-images.githubusercontent.com/57759540/84498683-1fa5b900-ac7f-11ea-9173-24facbe32af2.png)

Another example for you. I can confirm it’s when the analytical url is disabled.

**Comment by haoict** [comment]
https://github.com/haoict/twitter-no-ads/issues/10
