### ISSUE TITLE
Empty 'Trending' tab

### ISSUE THREAD

**Issue by LeoAnotherUser** [haoict/twitter-no-ads#6]
The following parts of the app stayed empty the whole time, I uninstalled the tweak and they were working again:

-For you
-COVID-19
-Trending
-News, Sports, Entertainment, Fun. 

iOS 13.5.
Unc0ver Jailbreak. 
iPhone 11.

**Comment by haoict** [comment]
You can go to Settings app -> Twitter No Ads and turn off "Remove News And Trending"
